### ISSUE TITLE
使用FusionFragment配合Viewpage使用白屏

### ISSUE THREAD

**Issue by DaguDuiyuan** [gtbluesky/fusion_issue_tracker#1]
需要点击切换页面后才能显示，是我使用方式有问题吗？

https://user-images.githubusercontent.com/19969616/215761621-ddac8dfc-e83a-45c6-b683-2931b4dfc9de.mp4

![WX20230131-203150](https://user-images.githubusercontent.com/19969616/215760873-3da1545f-8267-4048-b54c-8fb187c8db65.png)

**Comment by gtbluesky** [comment]
跑下example看下是否有问题

**Comment by DaguDuiyuan** [comment]
没看到example呀，我用的就是默认的计数器页面

**Comment by gtbluesky** [comment]
> 没看到example呀，我用的就是默认的计数器页面

去掉offscreenPageLimit试试

**Comment by DaguDuiyuan** [comment]
我直接用show() hide()了 ，但是切换fragment会闪一下，这个能解决吗

**Comment by gtbluesky** [comment]
> 

这样试试，我这边测试没问题，另外你用的Flutter版本是哪个？
    private fun showFragment(fragment: Fragment) {
        if (currentFragment == fragment) return
        val transaction = supportFragmentManager.beginTransaction()
        currentFragment?.let {
            transaction.hide(it)
        }
        currentFragment = fragment
        if (fragment.isAdded) {
            transaction.show(fragment)
        } else {
            transaction.add(binding.fl.id, fragment).show(fragment)
        }
        transaction.commit()
    }

**Comment by DaguDuiyuan** [comment]
您这边可以写一个demo吗，我测试了切换会闪一下，然后显示也有点问题
~~~
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (8 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
~~~
![WX20230201-151705](https://user-images.githubusercontent.com/19969616/215976674-827d75df-56f9-412d-b4a1-a043274aa378.png)

https://user-images.githubusercontent.com/19969616/215976995-ffff8495-1d53-438f-a835-b9ae79a91249.mp4

**Comment by gtbluesky** [comment]
> 您这边可以写一个demo吗，我测试了切换会闪一下，然后显示也有点问题
> 
> ```
> Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision b06b8b2710 (8 days ago) • 2023-01-23 16:55:55 -0800
> Engine • revision b24591ed32
> Tools • Dart 2.19.0 • DevTools 2.20.1
> ```
> 
> ![WX20230201-151705](https://user-images.githubusercontent.com/19969616/215976674-827d75df-56f9-412d-b4a1-a043274aa378.png)
> 
>  QQ20230201-151817-HD.mp4

setContentView后面调用这个方法
    private fun configureStatusBarForFullscreenFlutterExperience() {
        window.let {
            it.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS)
            it.statusBarColor = Color.TRANSPARENT
            it.decorView.systemUiVisibility =
                View.SYSTEM_UI_FLAG_LAYOUT_STABLE or View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
        }
    }
