### ISSUE TITLE
关于多页面嵌入问题

### ISSUE THREAD

**Issue by joker-fu** [gtbluesky/fusion_issue_tracker#3]
> 子页面模式
子页面模式是指一个或多个 Flutter 页面同时嵌入到 Native 容器中的场景，如：使用Tab切换Flutter和原生页面，Fusion 支持多个 Flutter 页面嵌入同一个 Native 容器中。

文档中看到支持嵌入同一 Native 容器，实测没有支持呢（2个 Flutter 页面（FusionFragment）放入同一个 Activity 中，类似PC QQ/微信 左右结构2个页面同时显示，非 Tab 切换）。

![image](https://user-images.githubusercontent.com/20105457/216496203-12b0db42-b593-4455-97d9-659998db1271.png)

**Comment by gtbluesky** [comment]
> > 子页面模式
> > 子页面模式是指一个或多个 Flutter 页面同时嵌入到 Native 容器中的场景，如：使用Tab切换Flutter和原生页面，Fusion 支持多个 Flutter 页面嵌入同一个 Native 容器中。
> 
> 文档中看到支持嵌入同一 Native 容器，实测没有支持呢（2个 Flutter 页面（FusionFragment）放入同一个 Activity 中，类似PC QQ/微信 左右结构2个页面同时显示，非 Tab 切换）。
> 
> ![image](https://user-images.githubusercontent.com/20105457/216496203-12b0db42-b593-4455-97d9-659998db1271.png)

文档这里描述的就是指Tab切换的场景，你说的这种Flutter单Engine模式下是没法实现同时展示两个Flutter页面的，基于EngineGroup虽然可以实现，但多Engine间内存不共享，数据来回拷贝比较麻烦，会导致内存占用比较高。
